import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'richard' at '1/10/17 8:23 PM' with Gradle 3.0
 *
 * @author richard, @date 1/10/17 8:23 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
